

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gerap
 */
public class VentanaGrafo extends javax.swing.JFrame {
    Grafo g = new Grafo();
    private int cv = 0;
    /**
     * Creates new form VentanaGrafo
     */
    public VentanaGrafo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIV = new javax.swing.JButton();
        btnEV = new javax.swing.JButton();
        btnIA = new javax.swing.JButton();
        btnEA = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCamino = new javax.swing.JTextField();
        btnCamino = new javax.swing.JButton();
        btnMA = new javax.swing.JButton();
        btnLA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextPane();
        cmbOrigen = new javax.swing.JComboBox<>();
        cmbDestino = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbVertices = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Dato: ");

        txtDato.setBackground(new java.awt.Color(153, 255, 255));
        txtDato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Origen:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Destino:");

        btnIV.setBackground(new java.awt.Color(153, 255, 255));
        btnIV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIV.setText("Insertar Vertice");
        btnIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIVActionPerformed(evt);
            }
        });

        btnEV.setBackground(new java.awt.Color(153, 255, 255));
        btnEV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEV.setText("Eliminar Vertice");
        btnEV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEVActionPerformed(evt);
            }
        });

        btnIA.setBackground(new java.awt.Color(153, 255, 255));
        btnIA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIA.setText("Insertar Arista");
        btnIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIAActionPerformed(evt);
            }
        });

        btnEA.setBackground(new java.awt.Color(153, 255, 255));
        btnEA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEA.setText("Eliminar Arista");
        btnEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEAActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Camino:");

        txtCamino.setBackground(new java.awt.Color(153, 255, 255));
        txtCamino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnCamino.setBackground(new java.awt.Color(153, 255, 255));
        btnCamino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCamino.setText("Verificar camino");
        btnCamino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminoActionPerformed(evt);
            }
        });

        btnMA.setBackground(new java.awt.Color(153, 255, 255));
        btnMA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMA.setText("Matriz Adyacencia");
        btnMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAActionPerformed(evt);
            }
        });

        btnLA.setBackground(new java.awt.Color(153, 255, 255));
        btnLA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLA.setText("Lista Adyacencia");
        btnLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLAActionPerformed(evt);
            }
        });

        txtMostrar.setEditable(false);
        txtMostrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));
        txtMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMostrar.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(txtMostrar);

        cmbOrigen.setBackground(new java.awt.Color(153, 255, 255));
        cmbOrigen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbOrigen.setSelectedIndex(-1);

        cmbDestino.setBackground(new java.awt.Color(153, 255, 255));
        cmbDestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Vertices:");

        cmbVertices.setBackground(new java.awt.Color(153, 255, 255));
        cmbVertices.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Formato: A-B-C...........");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCamino))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnIV))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel5)
                                        .addGap(12, 12, 12)
                                        .addComponent(cmbVertices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnIA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnCamino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIV)
                    .addComponent(btnEV)
                    .addComponent(jLabel5)
                    .addComponent(cmbVertices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btnIA)
                    .addComponent(btnEA)
                    .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCamino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCamino))
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMA)
                    .addComponent(btnLA))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIVActionPerformed
        char dato = txtDato.getText().toUpperCase().charAt(0);
            g.insertarVertice(dato);
            cmbOrigen.addItem(dato);
            cmbDestino.addItem(dato);
            cmbVertices.addItem(dato);
            cv++;
            setTitle("Se insertó correctamente el vertice " + dato);
    }//GEN-LAST:event_btnIVActionPerformed

    private void btnEVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEVActionPerformed
        char dato = (char) cmbVertices.getSelectedItem();
            cmbOrigen.removeItem(dato);
            cmbDestino.removeItem(dato);
            cmbVertices.removeItem(dato);
            setTitle("Se eliminó correctamente el vertice " + dato);
    }//GEN-LAST:event_btnEVActionPerformed

    private void btnIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIAActionPerformed
        g.insertarArista((char)cmbOrigen.getSelectedItem(), (char) cmbDestino.getSelectedItem());
    }//GEN-LAST:event_btnIAActionPerformed

    private void btnEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEAActionPerformed
        g.eliminarArista((char)cmbOrigen.getSelectedItem(), (char) cmbDestino.getSelectedItem());
    }//GEN-LAST:event_btnEAActionPerformed

    private void btnMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAActionPerformed
        boolean datos[][] = g.matrizAdyacencia();
        String m = "     ";
        for (int i = 0; i < cv; i++) {
            m = m + cmbVertices.getItemAt(i) + "  ";
        }
        for (int i = 0; i < cv; i++) {
            m = m + "\n" + cmbVertices.getItemAt(i) + "  ";
            for (int j = 0; j < cv; j++) {
                m += datos[i][j] ? "1 " : "0 ";
            }
        }
        txtMostrar.setText(m);
    }//GEN-LAST:event_btnMAActionPerformed

    private void btnLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLAActionPerformed
        if (cv > 0)
            txtMostrar.setText(g.listaAdy((char)cmbVertices.getSelectedItem()));
    }//GEN-LAST:event_btnLAActionPerformed

    private void btnCaminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminoActionPerformed
            String c = txtCamino.getText().trim().replaceAll("-", "");
            txtMostrar.setText(g.verificaCamino(c.toCharArray()));
    }//GEN-LAST:event_btnCaminoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGrafo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCamino;
    private javax.swing.JButton btnEA;
    private javax.swing.JButton btnEV;
    private javax.swing.JButton btnIA;
    private javax.swing.JButton btnIV;
    private javax.swing.JButton btnLA;
    private javax.swing.JButton btnMA;
    private javax.swing.JComboBox<Character> cmbDestino;
    private javax.swing.JComboBox<Character> cmbOrigen;
    private javax.swing.JComboBox<Character> cmbVertices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCamino;
    private javax.swing.JTextField txtDato;
    private javax.swing.JTextPane txtMostrar;
    // End of variables declaration//GEN-END:variables
}
